### ISSUE TITLE
Auto-publisher

### ISSUE THREAD

**Issue by jxn-30** [LEDBrain/Community-Service#451]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Having to publish announcements in announcement-channels is sometimes frustrating, especially when you forget to do so.
Also, having to manually publish messages that were sent automatically is easy to be forgotten.

This feature allows to (un-)select announcement-channels that should be published automatically

### ✔️ Solution

This feature allows to (un-)select announcement-channels that should be published automatically.

### 📝 Additional Context

In the message event:

```ts
if (message.channel.type === 'news' && pconfig.<listOfChannelsToCrosspostFrom>.includes(message.channel.id)) message.crosspost()
```
should work according to some old code of @kdev

**Comment by kdev** [comment]
I just looked it up and it seems like the [function still exists today ](https://discord.js.org/#/docs/discord.js/main/class/Message?scrollTo=crosspost).
Should be an easy one to implement

**Comment by kdev** [comment]
I will need to rewrite some of the `commands\Settings.ts` contents to make use of `ChannelSelectMenu`s and `RoleSelectMenu`s
